version: '3'
services:
  database:
    image: mysql:9.1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend:/backend
    networks:
      - rede1
  backend:
    container_name: backend
    build: backend/
    restart: always
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./backend:/back
    networks:
      - rede1
    depends_on:
      - database
networks:
   rede1:
volumes:
  mysql_data:
